### ISSUE TITLE
生成内容时字体报错 Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.

### ISSUE THREAD

**Issue by Modnars** [hooozen/hexo-theme-tranquility#23]
按照预设的配置生成页面时，执行 `hexo g` 会报错
```txt
Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.
```
简单排除了一下，应该是 `opentype.js` 产生的报错。在尝试修改其他字体、相同目录下放置其他字体并修改配置后均无法消除。每次生成内容时必现。
同时，对于一些中文（或和中文一起出现的英文）字符会丢失，导致正文内容存在很大的问题。

hexo 生成时报错如图：
<img width="1711" alt="image" src="https://github.com/hooozen/hexo-theme-tranquility/assets/22772190/08d48ffb-11db-4904-a320-81508a1fca80">

文字丢失场景（从上述问题的报错来看，应该是同一个问题）：
1）、配置中写的文字是 ModooZone
![image](https://github.com/hooozen/hexo-theme-tranquility/assets/22772190/1d1b0535-091e-423c-a683-6be5cc918bf2)
2）、页面生成后的字母 `d` 丢失了
![image](https://github.com/hooozen/hexo-theme-tranquility/assets/22772190/9db8649a-2d15-47c9-bb49-59a504f48da6)

希望得到你的关注与帮助，谢谢！

**Comment by Modnars** [comment]
我的环境信息：
```bash
$ hexo version
```
```txt
hexo: 6.3.0
hexo-cli: 4.3.1
os: darwin 22.5.0 13.4

node: 18.16.1
...
```

**Comment by hooozen** [comment]
你好,  我在本地进行了测试并未能重现该问题,  请检查主题是否更新到最新版本，该问题应该已经被解决了[#19](https://github.com/hooozen/hexo-theme-tranquility/issues/19#issuecomment-1566797831).  下面是我的测试环境和测试结果.  另外请**注意**,  涉及第三方字体的变动，请运行 `hexo clean` 后重新生成文件！

你提到的 `Undefined CHARARRAY encountered and treated as an empty string. This is probably caused by a missing glyph name.` “报错”确实是来自 opentype.js 的警告，但并不影响正常使用. 

以及你提到”导致正文内容存在很大的问题“，以防产生潜在的误解，主题文章内容的正文部分是没有使用任何第三方字体的. 

如以上建议无法解决问题，请继续反馈. 

```bash
hexo: 6.3.0
hexo-cli: 4.3.0
os: darwin 22.4.0 13.3
```

![截屏2023-07-09 20 23 38](https://github.com/hooozen/hexo-theme-tranquility/assets/24765496/b2665748-055a-464d-85bf-d475bbba59c0)

**Comment by Modnars** [comment]
确实，今天运行 `hexo clean` 并重新生成后，暂未发现有丢失字符的问题。

非常感谢！
